@startuml Matricula UFSM

Class Inscrição {
+ nome: String
+ Sobrenome: String
- Data de Nascimento: data
- Cpf: String
- Endereco: String
- Cidade: String
+ Ingresso: String
+ Curso: String
+ construtor (nome, sobrenome, Data de Nascimento, cpf, endereco, cidade, Ingresso, curso)
+ Obter Inscrição ()

}

Class Notas {
- Vestibular: integer = 6
- Redacao: String
- Entrevista: String
+ Status: String
+ construtor (Vestibular, Redacao, Entrevista)
+ Exibir Status ()
}

Class Matrícula {
+ Numero: integer
+ Campus: String
+ Grade curricular: String
+ Início do curso: data
+ construtor (Numero, Campus, Grade curricular, Início do curso)
}

Class Disciplinas {
+ Disciplina: String
+ Semestre: String
+ Turno: String
+ Professor: String
+ construtor (Disciplina, Semestre, Turno, Professor)
}

Inscrição --> Notas : Inscrição depende da Nota
Notas --> Matrícula
Matrícula --> Disciplinas

@enduml