@startuml Matricula UFSM

Class Inscrição {
+ nome: String
+ Sobrenome: String
- Data de Nascimento: data
- Cpf: String
- Endereco: String
- Cidade: String
+ Ingresso: String
+ Curso: String
+ construtor (nome, sobrenome, Data de Nascimento, cpf, endereco, cidade, Ingresso, curso)
+ Obter Inscrição ()
}

Class Vestibular {
- Nota: integer =<6
- Redacao: String
- Entrevista: String
+ construtor (Vestibular, Redacao, Entrevista)
}

Class Resultado {
+ Status: String
+ construtor (Status)
+ Exibir Status ()
}

Class Matricula {
+ Numero: integer
+ Campus: String
+ Grade curricular: String
+ Início do curso: data
+ construtor (Numero, Campus, Grade curricular, Início do curso)
}

Class Curso {
+ Departamento: String
+ Coordenador: String
+ Turno: String
+ construtor (Departamento, Coordenador, Turno)
}

Class Disciplina_ob {
+ Disciplina: String
+ Semestre: String
+ Turno: String
+ Professor: String
+ construtor (Disciplina, Semestre, Turno, Professor)
}

Class Disciplina_op {
+ Disciplina: String
+ Semestre: String
+ Turno: String
+ Professor: String
+ construtor (Disciplina, Semestre, Turno, Professor)
}

Inscrição --> Vestibular 
Vestibular --> Resultado
Resultado --> Matricula
Resultado --> Status : Matricula depende da Nota
Matricula --> Curso
Curso --> Disciplina_ob 
Curso --> Disciplina_op
@enduml